### ISSUE TITLE
Emojis now largely non-fuctional on Wordpress 

### ISSUE THREAD

**Issue by blakebo** [kevquirk/nineteen-quirky#1]
Hey Kev! I've loved using your theme for years on blakeboles.com. Just two weeks ago I noticed that most of my emojis (on both Wordpress menus and in content) were replaced by "X"s. I searched online and found no clear solution to this. My Wordpress is fully updated. No other big software changes. The error reproduced on friend's Macbooks, on my Google Pixel, and on multiple browsers. This doesn't seem like an issue actually related to your theme, but I thought I'd drop a line here just in case you knew of a solution, since emojis are so integral to the look of this theme. Thanks so much!
-Blake

**Comment by kevquirk** [comment]
Hey Blake,

Have you done anything that has required you to move your database by any chance? Like moving host or restoring from a backup?

If so, it's probably that. All the emojis are stored in the WP DB and moving/restoring the database usually breaks them. It's something to do with the emoji unicode characters, I think.

If it's not that, I'm fresh outta ideas I'm afraid. It's a theme issue though, as emojis are a client-side thing.

Thanks,

Kev

**Comment by blakebo** [comment]
Hey Kev,

Thanks so much for taking the time to respond!

I've consulted my host, and they are also puzzled. No major database changes, upgrades, moves, or other suspects. Double-checked the db charset too, it's all good. 

What's most weird is that some emojis still work (like ☕️  and 😻) but most others don't. Really strange.

Cheers,
Blake
